apiVersion: v1
kind: Service
metadata:
  name: hello-newdevops
  labels:
    app: hello-newdevops
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: hello-newdevops
    tier: hello-newdevops
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-newdevops
  labels:
    app: hello-newdevops
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hello-newdevops
        tier: hello-newdevops
    spec:
      containers:
      - image: registry-vpc.cn-huhehaote.aliyuncs.com/henryops/hello-newdevops:latest
        name: hello-newdevops
        ports:
        - containerPort: 80
          name: hello-newdevops
